#ifndef CHIMERA_TK_CONTROL_SYSTEM_ADAPTER_PV_MANAGER_DECL_H
#define CHIMERA_TK_CONTROL_SYSTEM_ADAPTER_PV_MANAGER_DECL_H

namespace ChimeraTK {
class PVManager;
}

#endif // CHIMERA_TK_CONTROL_SYSTEM_ADAPTER_PV_MANAGER_DECL_H
